//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digisoft.ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Exclude { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public Nullable<System.DateTime> DateofRelieving { get; set; }
        public string Skills { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string ExpWhenJoined { get; set; }
        public string PhoneNumber { get; set; }
        public string PersonalEmailAddress { get; set; }
        public string AlternatePhoneNumber { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactRelation { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string AadharNumber { get; set; }
        public string PanNumber { get; set; }
        public string CurrentCity { get; set; }
        public Nullable<int> CurrentStateId { get; set; }
        public Nullable<int> CurrentCountryId { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentCity { get; set; }
        public Nullable<int> PermanentStateId { get; set; }
        public Nullable<int> PermanentCountryId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string CurrentAddress { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual State State { get; set; }
        public virtual State State1 { get; set; }
    }
}
